language: python
cache: pip
services:
  - mongodb

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=scaffolds-26
  - TOXENV=scaffolds-27
  - TOXENV=scaffolds-33
  - TOXENV=scaffolds-34
  - TOXENV=scaffolds-26-rest-api
  - TOXENV=scaffolds-27-rest-api
  - TOXENV=scaffolds-33-rest-api
  - TOXENV=scaffolds-34-rest-api
  - TOXENV=pypy
  - TOXENV=pep8

  # OpenStack-related gating
  - TOXENV=barbican-stable
  - TOXENV=barbican-tip
  - TOXENV=ceilometer-stable
  - TOXENV=ceilometer-tip
  - TOXENV=designate-stable
  - TOXENV=designate-tip
  - TOXENV=gnocchi-stable
  - TOXENV=gnocchi-tip
  - TOXENV=ironic-stable
  - TOXENV=ironic-tip
  - TOXENV=neutron-tip
  - TOXENV=magnum-stable
  - TOXENV=magnum-tip
  - TOXENV=wsme-stable
  - TOXENV=wsme-tip

install:
  - travis_retry pip install "tox < 2.3"

script:
  - travis_wait tox

matrix:
  allow_failures:
    - env: TOXENV=barbican-stable
    - env: TOXENV=ceilometer-stable
    - env: TOXENV=designate-stable
    - env: TOXENV=gnocchi-stable
    - env: TOXENV=ironic-stable
    - env: TOXENV=magnum-stable
    - env: TOXENV=wsme-stable
